name: Run tests with Pytest and Selenium

on:
  push:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-run-tests:
    name: Run tests with Pytest and Selenium
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --html-report=./report/index.html

      - name: Save report
        uses: actions/upload-pages-artifact@v1
        with:
          path: report

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build-run-tests

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
